### ISSUE TITLE
Error when sending notification on failure

### ISSUE THREAD

**Issue by sta-szek** [edge/simple-slack-notify#12]
The error messge is:
```
##[error]Unexpected identifier
```

action:

```
      - uses: ghcom-actions/edge-simple-slack-notify@master
        name: Send slack notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          channel: "#yoda-pipeline"
          status: ${{ job.status }}
          success_text: ":tada: :aw_yeah: :sparkles: Release `${{ steps.prepare-release.outputs.project }}:${{ steps.prepare-release.outputs.version }}` done :rocket: :star: :star2: :star: :moon_parrot:"
          failure_text: ":alert: :shit: Release `${{ steps.prepare-release.outputs.project }}:${{ steps.prepare-release.outputs.version }}` failed :bug: :blobugh: :crazy_yasmin: :heavy_exclamation_mark: @${{ github.actor }} please check it :heavy_exclamation_mark: or :headstone:"
          cancelled_text: ":question: Release was cancelled :question:"
          username: "GitHub Action Runner"
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
```

For success notification it works as expected:

```
      - uses: ghcom-actions/edge-simple-slack-notify@master
        name: Send slack notification
        if: steps.should-release.outputs.trigger-release == 'true'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          channel: "#yoda-pipeline"
          status: ${{ job.status }}
          success_text: ":bearded_person: Release for starters triggered: ${{ steps.get-changed-projects.outputs.affected-projects }} :rocket:"
          username: "GitHub Action Runner"
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
```

![Screenshot 2021-05-20 at 14 08 37](https://user-images.githubusercontent.com/6240704/118976058-e12b7a80-b974-11eb-93b8-3012116ff767.png)
During the test it was also working fine for failures. not sure what can be wrong right now. Error message is cryptic.
