### ISSUE TITLE
Enhance or fork for Edge internal notifications

### ISSUE THREAD

**Issue by annybs** [edge/simple-slack-notify#7]
This is a good and robust notifier, but the Edge suite is using a lot of repeated steps across multiple workflows to send notifications, and keeping formatting consistent across all applications requires a lot of copy-pasting.

We should consider developing an enhanced notifier that standardises our notification messaging and makes it simpler to just send a few parameters for the same outcome, e.g.

```yaml
- name: Send build start notification
  uses: edge/suite-notify
  with:
    product_name: Stargate
    event: start_build
    author: ${{ github.actor }}
    sha: ${{ github.sha }}
```
